name: Build ISO

on:
  push:
      paths-ignore:
      - '**.md'
  pull_request:
        paths-ignore:
        - '**.md'
  

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: thevakhovske/holoiso:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Sanity check, if we are on SteamOS environment
        run: |
          cat /etc/os-release          
      
      - name: Install ArchISO
        run: |
          pacman --noconfirm -S git archiso wget

      - name: Build ISO File and mirror it
        run: |
          mkarchiso -v .
          find out/

      - uses: actions/upload-artifact@v2
        with:
          name: holoiso
          path: out/*.iso
